#!/usr/bin/env python
from BoxController import BoxController
import SecretCode


class StateMachine():
    def __init__(self):
        self.box_controller = BoxController()

    def log(self, message):
        print(message)

    def run(self):
        try:
            self.box_controller.open_box()
            while True:
                secret_code = SecretCode.get_secret_code()
                self.box_controller.close_box()
                self.wait_for_secret_code_match(secret_code)
                self.box_controller.open_box()
        except KeyboardInterrupt:
            self.log('Closing')
            self.box_controller.tear_down()

    def wait_for_secret_code_match(self, secret_code):
        '''
        Blocking IO call that waits for user input
        :param secret_code:
        :return:
        '''
        while True:
            user_code = raw_input()
            if user_code == secret_code:
                print('Secret code matched')
                return
            else:
                self.log('Secret code did not match')


state_machine = StateMachine()
state_machine.run()

print('Have a great day :D ')
